### PR TITLE
Add mergify configuration

### PR DESCRIPTION
**Pull request by okurz**
Add mergify configuration

### CODE REVIEW

**Comment by okurz** [comment]
wait, that does not look right

**Review by Martchus — APPROVED** [review]

**Comment by kraih** [comment]
Is mergify activated on openSUSE org level?

**Comment by okurz** [comment]
I don't know. I haven't asked yet

**Review by baierjan — APPROVED** [review]

**Comment by okurz** [comment]
I have requested for mergify to be added to the project scope using https://github.com/apps/mergify/installations/new and have asked in chat in https://matrix.to/#/!ilXMcHXPOjTZeauZcg:libera.chat/$xHF7LBlerFBrDDrpdDY_Xgl5gISRbx19NqPD2f9wXbw

**Pull request merged**
