### PR TITLE
Try to resolve "Uncaught ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined"

### PR DESCRIPTION
**Pull request by asdil12**

### CODE REVIEW

**Comment by kraih** [comment]
What are you trying to do? The worst case should be that you are pinning one or two dependencies to an older version.

**Comment by asdil12** [comment]
https://stackoverflow.com/a/75624439/1234176

**Comment by asdil12** [comment]
image


image

It seems that this var is not set to anything.

**Comment by kraih** [comment]
This approach does actually work and i've applied it in https://github.com/openSUSE/qem-dashboard/commit/8b0dda3d8d4a0ce782bb1db79b904366020687a0

**Pull request closed without merging**
