### PR TITLE
Rewrite the Frontend in Vue.js

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
The order of git commits no longer makes much sense as I cherry picked the webpack introduction. But squashing seems overly cruel

**Comment by coolo** [comment]
I leave this branch now for review, but there is one thing you'll notice when testing the deployment on http://e138.suse.de:3000 - the lastUpdated field isn't fetched. And the reason: I don't have a good idea yet how to do it without duplicating the auto update code in every view.

**Comment by kraih** [comment]
I would just squash it.

**Comment by coolo** [comment]
Did that now

**Pull request closed without merging**
