### PR TITLE
Fix condition for showing incidents introduced by 99b4127

### PR DESCRIPTION
**Pull request by Martchus**
* If there's only one incident we'd likely want to show it as well.
* Related ticket: https://progress.opensuse.org/issues/119557

### CODE REVIEW

**Comment by Martchus** [comment]
Note that there are no test changes because tests actually were failing and this fixes them.

**Comment by kraih** [comment]
How odd, the tests actually pass for me locally even without the patch.
```
$ TEST_ONLINE=postgres:///dashboard HARNESS_OPTIONS=j9 prove -l t/*.t
t/api_cleanup.t .. ok                                                   
t/json.t ......... ok                                                   
t/amqp.t ......... ok                                                   
t/api.t .......... ok                                                   
t/ui.t ........... ok   
All tests successful.
Files=5, Tests=25,  4 wallclock secs ( 0.03 usr  0.01 sys +  6.73 cusr  0.27 csys =  7.04 CPU)
Result: PASS
```

**Comment by kraih** [comment]
The change is obviously correct, but i'm still rather confused by the passing local tests (and bad fail report in the GitHub Action).

**Comment by Martchus** [comment]
Your glob isn't matching the `.js` test file and that is the one which is failing. (I reproduced the problem via `TEST_ONLINE=postgresql://postgres:postgres@localhost:5432/postgres prove -l t/ui.t.js -v`.)

**Comment by kraih** [comment]
The error is pretty obvious with the details:
```
$ TEST_ONLINE=postgres:///dashboard node TEST_HEADLESS=0 t/ui.t.js 
TAP version 13
# Subtest: Test dashboard ui
    # Subtest: Navigation
        ok 1 - should be equal
        ok 2 - should be equal
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equal
        ok 6 - should be equal
        1..6
    ok 1 - Navigation # time=4503.337ms
    
    # Subtest: Overview
        ok 1 - should match pattern provided
        ok 2 - should match pattern provided
        ok 3 - should match pattern provided
        ok 4 - should match pattern provided
        ok 5 - should match pattern provided
        ok 6 - should match pattern provided
        ok 7 - should be equal
        ok 8 - should be equal
        1..8
    ok 2 - Overview # time=170.142ms
    
    # Subtest: Filter blocked
        not ok 1 - page.waitForSelector: Timeout 30000ms exceeded. =========================== logs =========================== waiting for selector "tbody" to be visible ============================================================
          ---
          stack: |
            ============================================================
                Test.<anonymous> (file://t/ui.t.js:60:16)
          type: TimeoutError
          tapCaught: returnedPromiseRejection
          test: Filter blocked
          ...
        
        1..1
        # failed 1 test
    not ok 3 - Filter blocked # time=30066.593ms
    
    # Subtest: Incident popup
        ok 1 - should be equal
        ok 2 - should be equal
        1..2
    ok 4 - Incident popup # time=1010.067ms
    
    ok 5 - should be equivalent
    1..5
    # failed 1 of 5 tests
not ok 1 - Test dashboard ui # time=36069.447ms

1..1
# failed 1 test
# time=36071.347ms
```

**Pull request merged**
