### PR TITLE
Rewrite the Frontend in Vue.js (with live updates)

### PR DESCRIPTION
**Pull request by kraih**
This is a continuation of #4. I've upgraded to Vue.js 3 and added live updates for the 3 main pages.

### CODE REVIEW

**Comment by coolo** [comment]
Having fun?

**Comment by kraih** [comment]
Yes. 😁

**Comment by coolo** [comment]
If I go to http://localhost:3000/incident/21967 then follow the openqa link and go back I have an "Updating...." where there was last updated before. 

Just so you don't get bored

**Comment by kraih** [comment]
> If I go to http://localhost:3000/incident/21967 then follow the openqa link and go back I have an "Updating...." where there was last updated before.
> 
> Just so you don't get bored

Should be fixed now. I just made that page also live update. 😁

**Comment by kraih** [comment]
Gotta say, i'm really impressed with Vue.js so far. Those single file components make the code look very well organised.

**Comment by kraih** [comment]
This might be good enough now to merge and try in production.

**Review by coolo — APPROVED** [review]

**Pull request merged**
